all: AssignmentA AssignmentB

AssignmentA : AssignmentA.c
	gcc -o AssignmentA AssignmentA.c -lpthread

AssignmentB : AssignmentB.c
	gcc -o AssignmentB AssignmentB.c -lpthread

clean :
	rm AssignmentA AssignmentB
